export const QUESTIONS: string[] = [
  "Any marriage advice?",
  "Fun memory of the groom",
  "Fun memory of the bride",
  "Share a story about the couple",
  "Tell us a joke (any joke)",
  "Sing us a song",
  "Give us a fun fact (about anything)",
  "In one word, describe Jack and Jess as a couple",
  "Do you like our wedding (lol, please say yes)",
  "Predict Jack and Jess' future. What are we up to in 10 years?",
  "Show us a dance move",
  "Share a fact about the bride or groom",
  "Share a secret about the bride or groom that you've avoided telling us all these years",
  "Who is best dressed at the wedding besides the bride and groom?",
  "Tell us a conspiracy theory you believe in (don't go off the deep end in this confession though… just tell it to us quick)",
  "Describe Jack in 3 words",
  "Describe Jess in 3 words",
  "If the bride and groom's story were a movie, who is playing the bride? And the groom?",
  "Do your best impression of the White Lotus soundtrack",
  "Do your best impression of the “Defying Gravity” end riff",
];
